name: 'Renovate Automatic Branch'
description: 'Automatically create an empty branch to merge Renovate PR.'
branding:
  icon: "upload-cloud"
  color: "blue"

inputs:
  # CREDENTIALS
  github-token:
    description: 'Github Token'
    required: true
    default: ${{ github.token }}
  repo-owner:
    description: 'Repo Owner (the name of the org or user in the URL)'
    required: true
  repo-name:
    description: 'Repo Name'
    required: true
  branch-to-create:
    description: 'The branch name that will be created'
    required: false
    default: 'chore/renovateBaseBranch'
  branch-base:
    description: 'The branch name that will be used as base'
    required: false
    default: 'main'
  empty-commit-msg:
    description: 'The commit msg that will be created by the script'
    required: false
    default: 'chore: automatic empty commit'


runs:
  using: 'node16'
  main: 'build-ga/index.js'
