name: Test
on:
  workflow_dispatch:
    inputs:
      dry_run:
        required: true
        type: boolean
        default: 'true'
        description: 'DryRun?'

env:
  COMMIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/bodinsamuel/renovate-automatic-branch:1.0.0

    steps:
      - name: Test
