name: Test Docker
on:
  workflow_dispatch:
    inputs:
      dry_run:
        required: true
        type: boolean
        default: 'true'
        description: 'DryRun?'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Renovate Automatic Branch
        uses: bodinsamuel/renovate-automatic-branch@v1.0.2
        with:
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          repo-owner: bodinsamuel
          repo-name: renovate-automatic-branch
