name: Test
on:
  workflow_dispatch:
    inputs:
      dry_run:
        required: true
        type: boolean
        default: 'true'
        description: 'DryRun?'

env:
  RAB_GH_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
  RAB_OWNER: ${{ github.repository_owner }}
  RAB_REPO: renovate-automatic-branch
  # RAB_BRANCH_TO_CREATE:
  # RAB_BRANCH_BASE:
  # RAB_EMPTY_COMMIT_MSG:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: |
          docker run --rm -i \
            -e RAB_GH_TOKEN='${{ secrets.PERSONAL_GITHUB_TOKEN }}' \
            -e RAB_OWNER='${{ github.repository_owner }}' \
            -e RAB_REPO='renovate-automatic-branch' \
            ghcr.io/bodinsamuel/renovate-automatic-branch:1.0.0
