name: Test
on:
  schedule:
    - cron: '0 14 * * 5'
  workflow_dispatch:
    inputs:
      dry_run:
        required: true
        type: boolean
        default: 'true'
        description: 'DryRun?'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: |
          docker run --rm -i \
            -e RAB_GH_TOKEN='${{ secrets.PERSONAL_GITHUB_TOKEN }}' \
            -e RAB_OWNER='${{ github.repository_owner }}' \
            -e RAB_REPO='renovate-automatic-branch' \
            ghcr.io/bodinsamuel/renovate-automatic-branch:1.0.0
